name: CI
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  ci:
    uses: itsdarklikehell/ci-templates/.github/workflows/ci-python.yml@v1
    with:
      python-version: "3.12"
      manager: pip
      lint: true
      typecheck: false
      test: true
      build: false
